import type { Metadata } from "next";
import { Merriweather_Sans } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import Footer from "./components/Footer";

const merry = Merriweather_Sans({
  variable: "--font-merryweather-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={merry.variable}>
      <body className="bg-white text-gray-800 font-sans">
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
